name: $(Build.BuildId)

trigger:
 branches:
   include:
     - master/TestFixtureInitializer

variables:
- group: 'PipelineVariables'

# pool: TestAutomationExamples

# jobs:
# - job: default
#   timeoutInMinutes: 240
#   pool: TestAutomationExamples

#   steps:
#   - checkout: self
#     clean: true 

stages:  
  - stage: Build
    jobs:
      - job: Build
        pool: TestAutomationExamples
        steps:
          ### Initialize Container
          - template: $(Build.SourcesDirectory)\TestFixtureInitializer\Aure Pipeline Templates\initialize-container.yml@templates
            parameters:
              forceCreateImage: $(forceCreateImage)
              licenseUrl: $(LuxBeheerBcDevLicense)

          ### install specific test apps
        - task: ALOpsAppPublish@1
          displayName: 'ALOPS - Install specific test app(s)' 
          inputs:
            usedocker: true
            installaltesttool: true
            skip_verification: true
            install_al_app_names: |
              Tests-Cash Flow

          ### Compile and Cleanup
          - template: $(Build.SourcesDirectory)\TestFixtureInitializer\Aure Pipeline Templates\compile-publish.yml@templates
            parameters:
              navAppVersion: '1.0.[yyyyWW].*'
              runTestSuite: true
              disabledTests: '$(Build.SourcesDirectory)\TestFixtureInitializer\Test\DisabledTests\DisabledTests-CASH FLOW.json'
              createsqlbackup: '$(createSqlBackup)'